name: Test Build

on: workflow_dispatch

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: rokibhasansagar/slimhub_actions@main

      - name: ADDING ADITIONAL FILES

        run: |

          sudo apt install git

           cd ~/

           git clone https://github.com/akhilnarang/scripts

          cd scripts

          ./setup/android_build_env.sh
          - name: Init source repo

            run: |
           
            repo init depth=1 --no-repo-verify -u git://github.com/lighthouse-os/manifest.git -b sailboat -g default,-mips,-darwin,-notdefault
   
             repo sync -c --force-sync --no-tags --no-clone-bundle -j1 --optimized-fetch --prune
      - name: Clone device repo

        run: |

          git clone https://github.com/Dev786s/local-manifest.git --depth 1 -b main .repo/local_manifests

      
        
      - name: Start sync

        run: |

           

      - name: test rum

        run: |    
           build/envsetup.sh
           make bootimage

           make sepolicy

           make init

             

            

                

  
                
            

            

          


 

           


          

      
          

          

         






